on: [push]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v5
    - run: |
        python -m pip install --upgrade pip
        pip install pytest
    - run: |
        python tools/run_unit_tests.py


  static_analyzer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v5
    - run: |
        python -m pip install --upgrade pip
        pip install 'pylama[all]'
    - run: |
        python3 ./tools/static_analysis.py
