on: [push]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - run: |
        python -m pip install --upgrade pip
        pip install pytest
    - run: |
        python tools/build_unit_tests.py --run_tests